---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-yaml
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: just-fmt-check
        name: just fmt-check
        entry: just fmt-check
        language: system
        pass_filenames: false
      - id: just-lint
        name: just lint
        entry: just lint
        language: system
        pass_filenames: false
