general {
  after_sleep_cmd=hyprctl dispatch dpms on && $SCRIPT_DIR/github/quantumfate/scripts/wrapper/brightness.sh -r
  before_sleep_cmd=$SCRIPT_DIR/github/quantumfate/scripts/wrapper/brightness.sh -s && loginctl lock-session
  lock_cmd=pidof hyprlock || hyprlock -c $XDG_CONFIG_HOME/hypr-chezmoi/hyprlock.conf
}

listener {
  on-resume=brightnessctl -rd rgb:kbd_backlight
  on-timeout=brightnessctl -sd rgb:kbd_backlight set 0
  timeout=150
}

listener {
  on-resume=loginctl unlock-session
  on-timeout=loginctl lock-session && (pidof hyprlock || hyprlock -c $XDG_CONFIG_HOME/hypr-chezmoi/hyprlock.conf)
  timeout=300
}

listener {
  on-resume=hyprctl dispatch dpms on && $SCRIPT_DIR/github/quantumfate/scripts/wrapper/brightness.sh -r
  on-timeout=$SCRIPT_DIR/github/quantumfate/scripts/wrapper/brightness.sh -s && hyprctl dispatch dpms off
  timeout=330
}

listener {
  on-timeout=systemctl suspend
  timeout=1800
}
