general {
    after_sleep_cmd = hyprctl dispatch dpms on &&,brightness.sh -r
    before_sleep_cmd = ,brightness.sh -s && loginctl lock-session
    lock_cmd = pidof hyprlock || hyprlock --grace 120 -c $XDG_CONFIG_HOME/hypr-chezmoi/hyprlock.conf
    ignore_dbus_inhibit = false
}

# 2.5 min — dim keyboard backlight
listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume  = brightnessctl -rd rgb:kbd_backlight
}

# 5 min — lock the session
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume  = loginctl unlock-session
}

# 5.5 min — turn off displays
listener {
    timeout = 330
    on-timeout = ,brightness.sh -s && hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on && ,brightness.sh -r
}

# 15 min — suspend
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
