source = ~/.config/hypr/hypr/themes/macchiato.conf
background = $crust
base = $base
text = $text
alternate_base = $mantle
bright_text = $teal
accent = $mauve
accent_secondary = $pink
h1_size = 21
h2_size = 17
h3_size = 15
font_size = 13
small_font_size = 12
icon_theme = Papirus-Dark
font_family = DejaVuSansM Nerd Font
font_family_monospace = Inconsolata Nerd Font
