general {
    after_sleep_cmd = dms dpms on
    before_sleep_cmd = loginctl lock-session
    lock_cmd = dms ipc lock lock
    ignore_dbus_inhibit = false
}

# 2.5 min — dim keyboard backlight
listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume  = brightnessctl -rd rgb:kbd_backlight
}

# 5 min — lock the session
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume  = loginctl unlock-session
}

# 5.5 min — turn off displays
listener {
    timeout = 330
    on-timeout = dms dpms off
    on-resume  = dms dpms on
}

# 15 min — suspend
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
