# conf
source=~/.config/hypr/conf/animations.conf
source=~/.config/hypr/conf/binds.conf
source=~/.config/hypr/conf/windowrules.conf
source=~/.config/hypr/conf/workspaces.conf

## misc
source=~/.config/hypr/themes/mocha.conf
source=~/.config/hypr/conf/misc/alt-tab.conf
source=~/.config/hypr/conf/misc/named-windowrules.conf

## conditionals
source=~/.config/hypr-chezmoi/custom-sources.conf

exec-once=~/.config/hypr/scripts/IPC/IPC_Wrapper.sh

cursor {
  no_warps=true
}

decoration {
  blur {
    enabled=true
    ignore_opacity=true
    new_optimizations=true
    passes=3
    size=12
    xray=true
  }

  shadow {
    enabled=true
    range=2
  }
  active_opacity=1
  dim_around=0.6
  dim_special=0.4
  inactive_opacity=0.9
  rounding=0
}

dwindle {
  force_split=1
  preserve_split=true
  pseudotile=true
}


general {
  snap {
    enabled=true
    monitor_gap=30
  border_overlap=false
  }
  allow_tearing=false
  border_size=2
  col.active_border=$mauve
  col.inactive_border=$crust
  gaps_in=5
  gaps_out=10
  float_gaps=-1
  layout=master
  resize_on_border=false
  no_focus_fallback=true
}

group {
  groupbar {
    enabled=true
  }
  auto_group=true
}

input {
  touchpad {
    disable_while_typing=true
  }
  follow_mouse=0
  kb_layout=dvorak-custom
  mouse_refocus=false
  sensitivity=0.200000
}

layerrule=match:namespace notifications, animation slide

master {
  new_status=master
  orientation=center
  new_on_active=after
  mfact=0.50
  center_master_fallback=right
  always_keep_position=false
  slave_count_for_center_master=2
}

misc {
  disable_hyprland_logo=true
  disable_splash_rendering=true
  focus_on_activate=true
  font_family=Hack Nerd Font Mono
  size_limits_tiled=true
  mouse_move_enables_dpms=true
}

