#!/bin/sh

cd ~ || exit


## System
export CLUTTER_BACKEND="wayland"
export GDK_BACKEND="wayland,x11"
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

### Language
export LANG=en_GB.UTF-8:de_DE.UTF-8:it_IT.UTF-8
export LC_COLLATE=en_GB.UTF-8:de_DE.UTF-8:it_IT.UTF-8

### Applications
export BROWSER=brave
export EDITOR=nvim
export VISUAL=code

## Session
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

## Theming
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

unset QT_STYLE_OVERRIDE
exec Hyprland
