#!/usr/bin/env bash
# shellcheck disable=SC1091
cd ~ || exit

export SESSION_HYPR_SETTINGS_DIR="/tmp/hypr-session-settings"
export SESSION_HYPR_SETTINGS_MONITOR="monitor.conf"
export SESSION_HYPR_SETTINGS_WORKSPACE="workspace.conf"

mkdir -p $SESSION_HYPR_SETTINGS_DIR
echo "#Monitor settings" > $SESSION_HYPR_SETTINGS_DIR/$SESSION_HYPR_SETTINGS_MONITOR
echo "#Workspace settings" > $SESSION_HYPR_SETTINGS_DIR/$SESSION_HYPR_SETTINGS_WORKSPACE
## System
export CLUTTER_BACKEND="wayland"
export GDK_BACKEND="wayland,x11"
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

### Language
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC=de_DE.UTF-8
export LC_TIME=de_DE.UTF-8
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY=de_DE.UTF-8
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER=de_DE.UTF-8
export LC_NAME=de_DE.UTF-8
export LC_ADDRESS=de_DE.UTF-8
export LC_TELEPHONE=de_DE.UTF-8
export LC_MEASUREMENT=de_DE.UTF-8
export LC_IDENTIFICATION=de_DE.UTF-8

### Applications
export BROWSER=brave
export EDITOR=qvim
export VISUAL=code

## Session
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

## Theming
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=gtk2

## Source private env vars
while read -r line; do
    if [[ "$line" =~ ^\#.* ]]; then
        continue
    fi

    export "${line?}"
done < ~/.config/hypr/.env

unset QT_STYLE_OVERRIDE
exec Hyprland
