$mainMod = SUPER
$dofusScripts = ~/Projects/gitlab/dofus-scripts

bind = $mainMod, d, exec, ~/.config/hypr/scripts/toggle_submap.sh --on "Dofus Launch:dofus:reset"

submap = dofus
bind = , escape, exec, ~/.config/hypr/scripts/toggle_submap.sh --off "Dofus Launch:dofus:reset"

bind = , d, exec, $dofusScripts/dofus_toggle_launch.sh
bind = , a, exec, $dofusScripts/dofus_toggle_launch.sh --cra-team

# team_pioneer
bind = , ampersand, exec, ~/.config/hypr/scripts/toggle_submap.sh --on "Team Pioneer:team_pioneer:dofus"
submap = team_pioneer

bind=,F1, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Rejecter
bind=,F2, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Draintouch
bind=,F3, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Reminiscer
bind=,F4, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Traumafactory
bind=,F5, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Memoryfracture
bind=,F6, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Miserymaker
bind=,mouse:274, exec, $dofusScripts/do.sh --pioneer-team

bind = SHIFT, escape, exec, ~/.config/hypr/scripts/toggle_submap.sh --off "Team Pioneer:team_pioneer:dofus"
submap = dofus
# /team_pioneer

# team_cra
bind = , bracketleft, exec, ~/.config/hypr/scripts/toggle_submap.sh --on "Team Cra:team_cra:dofus"
submap = team_cra

bind=,F1, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Scars
bind=,F2, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Crudo
bind=,F3, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Athanasy
bind=,F4, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Hopeless
bind=,F5, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Choke
bind=,F6, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Deathwish
bind=,F7, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Drowning
bind=,F8, exec, /home/quantum/.config/hypr/scripts/wrapper/processFn.sh Room
bind=,mouse:274, exec, $dofusScripts/do.sh --cra-team

bind = SHIFT, escape, exec, ~/.config/hypr/scripts/toggle_submap.sh --off "Team Cra:team_cra:dofus"
submap = dofus
# /team_cra

submap = reset
