windowrule {
    name = opaque-media-browser
    enable = false
    match:tag = media-browser
    opacity = 1 override
}

windowrule {
    name = opaque-default-browser
    enable = false
    match:tag = default-browser
    opacity = 1 override
}

windowrule {
    name = feh
    workspace = special:feh
    float = true
    content = photo
    center = true
    rounding = 0
    opacity = 1 1 override
    match:initial_class = feh
}

windowrule {
    name = workspace-spotify
    enable = true
    workspace = special:spotify
    match:initial_class = ([Ss]potify)
}

windowrule {
    name = workspace-vesktop
    enable = true
    workspace = special:vesktop
    match:initial_class = vesktop
}
