-- Animations & bezier curves (ported from conf/animations.conf).

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1.0}  } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("defout",         { type = "bezier", points = { {0.16, 1},    {0.3, 1}     } })
hl.curve("overshot",       { type = "bezier", points = { {0.18, 0.95}, {0.22, 1.03} } })
hl.curve("smoothOut",      { type = "bezier", points = { {0.5, 0},     {0.99, 0.99} } })
hl.curve("smoothIn",       { type = "bezier", points = { {0.5, -0.5},  {0.68, 1.5}  } })

hl.config({ animations = { enabled = true } })

hl.animation({ leaf = "global",              enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",              enabled = true, speed = 3,    bezier = "default" })
hl.animation({ leaf = "windows",             enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",           enabled = true, speed = 3,    bezier = "default" })
hl.animation({ leaf = "windowsOut",          enabled = true, speed = 3,    bezier = "default" })
hl.animation({ leaf = "fadeIn",              enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",             enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",                enabled = true, speed = 3,    bezier = "default" })
hl.animation({ leaf = "layers",              enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",            enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",           enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",        enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut",       enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",          enabled = true, speed = 5,    bezier = "default" })
hl.animation({ leaf = "windowsMove",         enabled = true, speed = 4,    bezier = "default" })
hl.animation({ leaf = "specialWorkspaceIn",  enabled = true, speed = 5,    bezier = "default", style = "slidefadevert" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 5,    bezier = "defout",  style = "slidefadevert" })
