# Tags

## Browser
windowrule = tag +default-browser, match:initial_class ([fF]irefox|zen|zen-twilight|zen-beta)
windowrule = tag +media-browser, match:initial_class (zen-twilight-media)

## App Categories
windowrule = tag +terminal, match:class (Alacritty|kitty|ghostty|foot)
windowrule = tag +pip, match:title (Picture.?in.?[Pp]icture)
windowrule = tag +pip, match:initial_title Discord Popout

## Floating Windows
windowrule = tag +floating-window, match:class (protonvpn-app|Impala|About|Wiremix|com.gabm.satty|Calos|TUI.float|io\.github\.Qalculate\.qalculate-qt|Proton Pass)
windowrule = tag +floating-window, match:class (Ranger-tui|Wiremix-tui|Btop-tui|Parui-tui|Blue-tui)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-hyprland|xdg-desktop-portal-gtk|sublime_text|DesktopEditors), match:title (Open.*Files?|Save.*Files?|Save.*As|All Files|Save)
windowrule = tag +floating-window, match:class (zen|zen-twilight|zen-beta), match:title (Library)
windowrule = tag +floating-window, match:class (org\.keepassxc\.KeePassXC), match:title (Unlock Database - KeePassXC)

# Workspaces
windowrule = workspace 1, match:class (Kitty-Main|Tmux-Main)
windowrule = workspace 1, match:initial_class zen-twilight
windowrule = workspace 2, match:class (obsidian)
windowrule = workspace 3, match:class (Proton Mail)
windowrule = workspace 6, match:tag media-browser
windowrule = workspace special:obs, match:initial_class com.obsproject.Studio

# Picture in Picture (tag: pip)
windowrule = float on, match:tag pip
windowrule = pin on, match:tag pip
windowrule = size 600 338, match:tag pip
windowrule = keep_aspect_ratio on, match:tag pip
windowrule = border_size 0, match:tag pip
windowrule = opacity 1 1 override, match:tag pip
windowrule = move 100%-w-40 4%, match:tag pip

# Floating Windows (tag: floating-window)
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 1400 1000, match:tag floating-window

## One-off Floats
windowrule = float on, match:class (ffplay|clipse|Kitty-float)
windowrule = size 800 600, match:class (clipse)
windowrule = size 640 360, match:class (Kitty-float)
windowrule = center on, match:class (Kitty-float)

## Steam floats
windowrule = float on, match:title (Steam Settings|Friends List)

# Tiling Overrides
windowrule = tile on, match:tag chromium-based-browser

# Focus/Behaviour
windowrule = suppress_event activatefocus, match:class (vesktop|whatsapp-electron)
windowrule = suppress_event activate, match:class (vesktop|whatsapp-electron)

# Opacity
windowrule = opacity 1 1, match:class ^(zoom|vlc|mpv|mp4|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
