workspace=1,monitor:DP-1,persistent:true,default:true
workspace=2,monitor:DP-1,persistent:true
workspace=3,monitor:DP-1,persistent:true
workspace=4,monitor:DP-1,persistent:true
workspace=5,monitor:DP-1
workspace=6,monitor:HDMI-A-1

workspace=s[true]m[DP-1]n[e:feh], name:feh
workspace=s[true]n[e:spotify], name:spotiy, on-created-empty:spotify
