workspace=1, persistent:true, default:true
workspace=2, persistent:true
workspace=3, persistent:true
workspace=4
workspace=5, gapsin:0, gapsout:0, bordersize:0
workspace=6, orientation:right
workspace=7, orientation:right
workspace=8, orientation:right
workspace=9, orientation:right
workspace=10, orientation:right

workspace=s[true]n[e:feh], name:feh
workspace=s[true]n[e:spotify], name:spotiy, on-created-empty:spotify
workspace=s[true]n[e:vesktop], name:vesktop, on-created-empty:vesktop
