require("hypr.conf")
require("hypr.workspaces")
require("hypr.events")
require("hypr.layouts")
require("hypr.services")
require("hypr.themes")

require("hypr.animations")
require("hypr.binds")
require("hypr.layerrules")
require("hypr.monitors")
require("hypr.windowrules")
