---@meta

---Global config table populated by hyprland.lua entry point.
---@type Config
config = nil

---@class Config
---@field main_mod string
---@field peek_delay_ms integer Dwell time in a submap before the passive peek cheatsheet fades in.
---@field primary_mod string
---@field secondary_mod string
---@field tertiary_mod string
---@field app_cmds Commands
---@field host_configs table<string, Hosts> Per-host definitions, keyed by hostname.
---@field host Hosts The current host's config, resolved at load. Use this everywhere.

---@class Workspaces
---@field workspace_specs HL.WorkspaceRuleSpec[]
---@field workspace_keys string[]

---@class Commands
---@field media_browser string
---@field main_browser string
---@field dev_browser string
---@field terminal string
---@field terminal_float string
---@field tmux string
---@field password_manager string
---@field mail string
---@field calculator string
---@field volume_control string
---@field app_launcher string
---@field package_manager_ui string

---@class Hosts
---@field primary_monitor string
---@field secondary_monitor string?
---@field hyprlock_conf string
---@field kb_options string?
---@field workspaces Workspaces

---@class WindowRuleProps
---@field class	string?	Windows with class matching RegEx.
---@field title	string?	Windows with title matching RegEx.
---@field initial_class	string?	Windows with initialClass matching RegEx.
---@field initial_title	string?	Windows with initialTitle matching RegEx.
---@field tag	string?	Windows with matching tag.
---@field xwayland	boolean?	Xwayland windows.
---@field float	boolean?	Floating windows.
---@field fullscreen	boolean?	Fullscreen windows.
---@field pin	boolean?	Pinned windows.
---@field focus	boolean?	Currently focused window.
---@field group	boolean?	Grouped windows.
---@field modal	boolean?	Modal windows (e.g. “Are you sure” popups)
---@field fullscreen_state_client	integer?	Windows with matching fullscreenstate. 0 - none, 1 - maximize, 2 - fullscreen, 3 - maximize and fullscreen.
---@field fullscreen_state_internal	integer?	Windows with matching fullscreenstate. 0 - none, 1 - maximize, 2 - fullscreen, 3 - maximize and fullscreen.
---@field workspace	string?	Windows on matching workspace. Can be id, "name:string" or a workspace selector.
---@field content	string?	Windows with specified content type (none, photo, video, game).
---@field xdg_tag	string?	Match a window by its xdgTag (see hyprctl clients to check if it has one).

---Group rule string. Space-separate options to combine (e.g. "barred set", "lock always").
---@alias HL.WindowGroup
---| "set"           # Open window as a group.
---| "set always"    # Open as group; always effective (not just first window).
---| "new"           # Shorthand for "barred set".
---| "lock"          # Lock the group. Combine with "set" or "new".
---| "lock always"   # Lock the group; always effective.
---| "barred"        # Do not auto-group into focused unlocked group.
---| "deny"          # Disallow toggling as/adding to a group.
---| "invade"        # Force open window in locked group.
---| "override"      # Override other group rules. Combine with other options.
---| "unset"         # Clear all group rules.
---| string

---@alias HL.ContentType "none"|"photo"|"video"|"game"
---@alias HL.IdleInhibit "none"|"always"|"focus"|"fullscreen"

---Effects evaluated once at window open. initialClass/initialTitle used for matching.
---@class WindowRuleStaticEffects
---@field float	boolean?	Floats a window.
---@field tile	boolean?	Tiles a window.
---@field fullscreen	boolean?	Fullscreens a window.
---@field maximize	boolean?	Maximizes a window.
---@field fullscreen_state	string?	Sets fullscreen mode, e.g. "1 2" (internal client). 0 none, 1 maximize, 2 fullscreen, 3 both.
---@field move	(string|number)[]?	Moves floating window, monitor-local. E.g. {100, 200} or expression strings.
---@field size	(string|number)[]?	Resizes floating window. E.g. {800, 600} or expression strings.
---@field center	boolean?	Centers floating window on monitor.
---@field pseudo	boolean?	Pseudotiles a window.
---@field monitor	string?	Sets monitor to open on. E.g. "1" or "DP-1". Suffix " silent".
---@field workspace	string?	Sets workspace to open on. "unset" or suffix " silent".
---@field no_initial_focus	boolean?	Disables initial focus.
---@field pin	boolean?	Pin to all workspaces. Floating only.
---@field group	HL.WindowGroup?	Sets group properties. Bare key = "set".
---@field suppress_event	string?	Ignore events. Space-separated: "fullscreen", "maximize", "activate", "activatefocus", "fullscreenoutput".
---@field content	HL.ContentType?	Sets content type.
---@field no_close_for	integer?	Block killactive for N ms after open.
---@field scrolling_width	number?	Column width for scrolling layout workspaces.

---Effects re-evaluated on property change. All also settable via setprop.
---@class WindowRuleDynamicEffects
---@field persistent_size	boolean?	Restore stored size for floating windows of same class/title.
---@field no_max_size	boolean?	Remove max size limitations.
---@field stay_focused	boolean?	Force focus while window visible.
---@field animation	string?	Force animation, optional style. E.g. "popin" or "popin 80%".
---@field border_color	string|table?	Force border color. Color, gradient, or {colors={...}, angle=N}.
---@field idle_inhibit	HL.IdleInhibit?	Idle inhibit rule.
---@field opacity	string?	Opacity multiplier. "0.8", "0.9 0.7" (active/inactive), "1 0.8 0.9" (active/inactive/fullscreen). Append " override" for absolute.
---@field tag	string?	Apply tag. "+t" set, "-t" unset, "t" toggle.
---@field max_size	(string|number)[]?	Max size for floating. E.g. {800, 600}.
---@field min_size	(string|number)[]?	Min size for floating. E.g. {200, 150}.
---@field border_size	integer?	Border size.
---@field rounding	integer?	Force rounding px, ignore default.
---@field rounding_power	number?	Override rounding power.
---@field allows_input	boolean?	Force XWayland window to receive input.
---@field dim_around	boolean?	Dim around window. Floating only.
---@field decorate	boolean?	Draw window decorations. (default: true)
---@field focus_on_activate	boolean?	Focus app on activation request.
---@field keep_aspect_ratio	boolean?	Force aspect ratio on mouse resize.
---@field nearest_neighbor	boolean?	Force nearest-neighbor filtering.
---@field no_anim	boolean?	Disable animations.
---@field no_blur	boolean?	Disable blur.
---@field no_dim	boolean?	Disable window dimming.
---@field no_focus	boolean?	Disable focus.
---@field no_follow_mouse	boolean?	Block focus on mouse-over when follow_mouse=1.
---@field no_shadow	boolean?	Disable shadows.
---@field no_shortcuts_inhibit	boolean?	Disallow shortcut inhibition.
---@field no_screen_share	boolean?	Hide from screen sharing.
---@field no_vrr	boolean?	Disable VRR. Needs misc.vrr = 2 or 3.
---@field opaque	boolean?	Force opaque.
---@field force_rgbx	boolean?	Ignore alpha channel entirely.
---@field sync_fullscreen	boolean?	Sync fullscreen mode with window-sent mode.
---@field immediate	boolean?	Allow tearing.
---@field xray	boolean?	Blur xray mode.
---@field render_unfocused	boolean?	Render as if visible when hidden.
---@field scroll_mouse	number?	Override input.scroll_factor.
---@field scroll_touchpad	number?	Override input.touchpad.scroll_factor.
---@field confine_pointer	boolean?	Lock cursor to window.

---@class WindowRuleEffects
---@field static WindowRuleStaticEffects?
---@field dynamic WindowRuleDynamicEffects?

---@class WindowRuleScope
---@field props WindowRuleProps[]
---@field effects WindowRuleStaticEffects

--- Submap trees (hypr/lib/submap.lua) -------------------------------------

---One node of a submap tree. A *leaf* has an `action`; a *group* has `entries`
---and opens a nested submap. A group may also carry an `action`, run just
---before it is entered. One class covers both so trees nest uniformly.
---@class SubmapEntry
---@field key string Key that triggers this entry within its submap (e.g. "s", "F1", "mouse:274").
---@field mods? string[] Modifiers held with `key` (e.g. { "CTRL" }, { config.main_mod, "ALT" }).
---@field desc? string Description; shown in the cheatsheet.
---@field action? HL.Dispatcher|fun() Leaf: runs on press. Group: runs before entering.
---@field entries? SubmapEntry[] Present => a navigable group (nested submap).
---@field name? string Group submap name; defaults to "<parent>-<key>".
---@field stay? boolean Leaf: stay in the submap after running instead of exiting. Overrides `sticky`.
---@field sticky? boolean Group: default `stay` for descendant leaves (modal submap). Inherited by children.
---@field repeating? boolean Leaf: allow key repeat while held.
---@field on_enter? fun() Group: runs just after this submap becomes active (e.g. sync external UI state).
---@field on_leave? fun() Group: runs when this submap is popped (back / leaf exit / reset).
---@field opts? HL.BindOptions Extra bind options merged into the keybind (e.g. release, transparent).

---A which-key style submap tree, opened by a keystroke. Passed to `submap.tree`.
---@class SubmapSpec
---@field mods string[] Keystroke that opens the root submap (e.g. { config.main_mod, "s" }).
---@field name string Root submap name.
---@field desc? string Description for the opening keybind (cheatsheet); defaults to `name`.
---@field sticky? boolean Leaves stay in the submap by default (modal); default false.
---@field on_enter? fun() Runs just after the root submap becomes active.
---@field on_leave? fun() Runs when the root submap is popped (tree fully exited).
---@field entries SubmapEntry[] The submap's entries.
