#!/usr/bin/env bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

function run() {
  # check if the program is installed and executable
  if which "$1" > /dev/null; then
    # check if the program is already running
    if ! pgrep -f "$1" > /dev/null; then
      # execute the program if it is not running
      eval "$@" &
    fi
  else
    # output an error message if the program is not installed or executable
    echo "Error: program $1 is not installed or executable."
    echo "$1" >> notinstalled
  fi
}

# Launch monitor configuration daemon (kanshi)
"${SCRIPTSDIR}"/devices/displayprofiles &
sleep 1

# Apply themes
"${SCRIPTSDIR}"/appearance/gtkthemes &

# Lauch notification daemon (mako)
"${SCRIPTSDIR}"/interaction/notifications &

# Lauch statusbar (waybar)
"${SCRIPTSDIR}"/appearance/statusbar &

run nm-applet
run redshift-gtk -l "$LOCATION_LAT":"$LOCATION_LON"
run caffeine
run pamac-tray
run xfce4-power-manager
run numlockx on
run udiskie -a -s --terminal=Alacrity
run pdfwatcher.sh
run dropbox
run aerc
run spotify
run discord
run pdfwatcher.sh
#run telegram-desktop
